version: 0.2

phases:
  install:
    commands:
      - echo "Installing Java 17 manually"
      - yum install -y java-17-amazon-corretto-devel
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
  build:
    commands:
      - java -version
      - mvn clean package
artifacts:
  files:
    - unicorn-web-project.war   # WAR file jo target folder me banta hai
  base-directory: target         # CodeBuild yahan se artifact pick karega

