version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Building Unicorn Project with Java 17"
      - mvn clean install
artifacts:
  files:
    - target/*.jar
